[package]
name = "csvread"
version = "0.1.0"
authors = ["Sebastien Castiel <sebastien@castiel.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
csv = "1.1"
tabular = "0.1.4"
nom = "6.0.0"
